<?php

use Illuminate\Database\Seeder;

class ClotheSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('clothes')->insert([
            ['name' => 'Hokusai Blue 1', 'image' => 'images\wave.jpg', 'stock' => 7, 'price' => 280000, 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper, est non lobortis rutrum, lorem sapien maximus elit, in laoreet tellus augue eget dui. Maecenas libero enim, commodo ut ipsum sit amet, elementum sodales lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut elementum velit. Duis at dolor fringilla, pharetra nibh non, sodales arcu. Donec est justo, gravida quis dolor faucibus, pretium maximus nisl. Sed at nunc vel massa imperdiet laoreet. Sed vel tristique mi. Quisque luctus, nisi non tristique varius, justo urna euismod nibh, eu imperdiet lorem sem vel mi. Aenean sed consectetur erat, nec volutpat eros. Sed ut rhoncus tortor, quis laoreet nibh. Maecenas quis dolor a quam congue accumsan. Nulla eu laoreet urna, at consectetur magna. Fusce enim ligula, sodales quis convallis eu, vestibulum ac justo. Nulla ac interdum sapien. Vestibulum id diam facilisis, ornare arcu at, porttitor ex. Nunc facilisis nibh ac nibh rutrum mollis. Nullam justo diam, elementum convallis sollicitudin id, finibus ac mauris. Aenean porta, mauris sit amet luctus bibendum, purus leo ornare ante, eu efficitur ipsum ligula quis nibh. Integer ut erat id justo maximus tincidunt quis at elit. Quisque efficitur mauris ac nunc placerat, vel porttitor ante iaculis. Curabitur volutpat nisi sit amet ex ultrices, et placerat erat dapibus.'],
            ['name' => 'Hokusai Blue 2', 'image' => 'images\mountain.jpg', 'stock' => 15, 'price' => 280000, 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper, est non lobortis rutrum, lorem sapien maximus elit, in laoreet tellus augue eget dui. Maecenas libero enim, commodo ut ipsum sit amet, elementum sodales lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut elementum velit. Duis at dolor fringilla, pharetra nibh non, sodales arcu. Donec est justo, gravida quis dolor faucibus, pretium maximus nisl. Sed at nunc vel massa imperdiet laoreet. Sed vel tristique mi. Quisque luctus, nisi non tristique varius, justo urna euismod nibh, eu imperdiet lorem sem vel mi. Aenean sed consectetur erat, nec volutpat eros. Sed ut rhoncus tortor, quis laoreet nibh. Maecenas quis dolor a quam congue accumsan. Nulla eu laoreet urna, at consectetur magna. Fusce enim ligula, sodales quis convallis eu, vestibulum ac justo. Nulla ac interdum sapien. Vestibulum id diam facilisis, ornare arcu at, porttitor ex. Nunc facilisis nibh ac nibh rutrum mollis. '],
            ['name' => 'Hokusai Blue 3', 'image' => 'images\fisher.jpg', 'stock' => 10, 'price' => 300000, 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper, est non lobortis rutrum, lorem sapien maximus elit, in laoreet tellus augue eget dui. Maecenas libero enim, commodo ut ipsum sit amet, elementum sodales lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut elementum velit. Duis at dolor fringilla, pharetra nibh non, sodales arcu. Donec est justo, gravida quis dolor faucibus, pretium maximus nisl. Sed at nunc vel massa imperdiet laoreet. Sed vel tristique mi. Quisque luctus, nisi non tristique varius, justo urna euismod nibh, eu imperdiet lorem sem vel mi. Aenean sed consectetur erat, nec volutpat eros. Sed ut rhoncus tortor, quis laoreet nibh. Maecenas quis dolor a quam congue accumsan. Nulla eu laoreet urna, at consectetur magna. Fusce enim ligula, sodales quis convallis eu, vestibulum ac justo. Nulla ac interdum sapien. Vestibulum id diam facilisis, ornare arcu at, porttitor ex. Nunc facilisis nibh ac nibh rutrum mollis. Nullam justo diam, elementum convallis sollicitudin id, finibus ac mauris.'],
            ['name' => 'Hokusai Blue 4', 'image' => 'images\sailing.jpg', 'stock' => 8, 'price' => 290000, 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper, est non lobortis rutrum, lorem sapien maximus elit, in laoreet tellus augue eget dui. Maecenas libero enim, commodo ut ipsum sit amet, elementum sodales lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut elementum velit. Duis at dolor fringilla, pharetra nibh non, sodales arcu. Donec est justo, gravida quis dolor faucibus, pretium maximus nisl. Sed at nunc vel massa imperdiet laoreet. Sed vel tristique mi. Quisque luctus, nisi non tristique varius, justo urna euismod nibh, eu imperdiet lorem sem vel mi. Aenean sed consectetur erat, nec volutpat eros. Sed ut rhoncus tortor, quis laoreet nibh. Maecenas quis dolor a quam congue accumsan. Nulla eu laoreet urna, at consectetur magna. Fusce enim ligula, sodales quis convallis eu, vestibulum ac justo.'],
            ['name' => 'Hokusai Blue 5', 'image' => 'images\manywaves.jpg', 'stock' => 7, 'price' => 280000, 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper, est non lobortis rutrum, lorem sapien maximus elit, in laoreet tellus augue eget dui. Maecenas libero enim, commodo ut ipsum sit amet, elementum sodales lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut elementum velit. Duis at dolor fringilla, pharetra nibh non, sodales arcu. Donec est justo, gravida quis dolor faucibus, pretium maximus nisl. Sed at nunc vel massa imperdiet laoreet. Sed vel tristique mi. Quisque luctus, nisi non tristique varius, justo urna euismod nibh, eu imperdiet lorem sem vel mi. Aenean sed consectetur erat, nec volutpat eros. Sed ut rhoncus tortor, quis laoreet nibh. Maecenas quis dolor a quam congue accumsan. Nulla eu laoreet urna, at consectetur magna. Fusce enim ligula, sodales quis convallis eu, vestibulum ac justo. Nulla ac interdum sapien. Vestibulum id diam facilisis, ornare arcu at, porttitor ex. Nunc facilisis nibh ac nibh rutrum mollis. Nullam justo diam, elementum convallis sollicitudin id, finibus ac mauris. Aenean porta, mauris sit amet luctus bibendum, purus leo ornare ante, eu efficitur ipsum ligula quis nibh. Integer ut erat id justo maximus tincidunt quis at elit. Quisque efficitur mauris ac nunc placerat, vel porttitor ante iaculis. Curabitur volutpat nisi sit amet ex ultrices, et placerat erat dapibus.'],
            ['name' => 'Hokusai Blue 6', 'image' => 'images\manywaves2.jpg', 'stock' => 15, 'price' => 280000, 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper, est non lobortis rutrum, lorem sapien maximus elit, in laoreet tellus augue eget dui. Maecenas libero enim, commodo ut ipsum sit amet, elementum sodales lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut elementum velit. Duis at dolor fringilla, pharetra nibh non, sodales arcu. Donec est justo, gravida quis dolor faucibus, pretium maximus nisl. Sed at nunc vel massa imperdiet laoreet. Sed vel tristique mi. Quisque luctus, nisi non tristique varius, justo urna euismod nibh, eu imperdiet lorem sem vel mi. Aenean sed consectetur erat, nec volutpat eros. Sed ut rhoncus tortor, quis laoreet nibh. Maecenas quis dolor a quam congue accumsan. Nulla eu laoreet urna, at consectetur magna. Fusce enim ligula, sodales quis convallis eu, vestibulum ac justo. Nulla ac interdum sapien. Vestibulum id diam facilisis, ornare arcu at, porttitor ex. Nunc facilisis nibh ac nibh rutrum mollis. '],
            ['name' => 'Hokusai Blue 7', 'image' => 'images\slide.jpg', 'stock' => 10, 'price' => 300000, 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper, est non lobortis rutrum, lorem sapien maximus elit, in laoreet tellus augue eget dui. Maecenas libero enim, commodo ut ipsum sit amet, elementum sodales lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut elementum velit. Duis at dolor fringilla, pharetra nibh non, sodales arcu. Donec est justo, gravida quis dolor faucibus, pretium maximus nisl. Sed at nunc vel massa imperdiet laoreet. Sed vel tristique mi. Quisque luctus, nisi non tristique varius, justo urna euismod nibh, eu imperdiet lorem sem vel mi. Aenean sed consectetur erat, nec volutpat eros. Sed ut rhoncus tortor, quis laoreet nibh. Maecenas quis dolor a quam congue accumsan. Nulla eu laoreet urna, at consectetur magna. Fusce enim ligula, sodales quis convallis eu, vestibulum ac justo. Nulla ac interdum sapien. Vestibulum id diam facilisis, ornare arcu at, porttitor ex. Nunc facilisis nibh ac nibh rutrum mollis. Nullam justo diam, elementum convallis sollicitudin id, finibus ac mauris.'],
            ['name' => 'Hokusai Blue 8', 'image' => 'images\wheel.jpg', 'stock' => 8, 'price' => 290000, 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper, est non lobortis rutrum, lorem sapien maximus elit, in laoreet tellus augue eget dui. Maecenas libero enim, commodo ut ipsum sit amet, elementum sodales lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut elementum velit. Duis at dolor fringilla, pharetra nibh non, sodales arcu. Donec est justo, gravida quis dolor faucibus, pretium maximus nisl. Sed at nunc vel massa imperdiet laoreet. Sed vel tristique mi. Quisque luctus, nisi non tristique varius, justo urna euismod nibh, eu imperdiet lorem sem vel mi. Aenean sed consectetur erat, nec volutpat eros. Sed ut rhoncus tortor, quis laoreet nibh. Maecenas quis dolor a quam congue accumsan. Nulla eu laoreet urna, at consectetur magna. Fusce enim ligula, sodales quis convallis eu, vestibulum ac justo.']
        ]); 
    }
}
